# This is a basic workflow to help you get started with Actions

name: Create release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags: [ "v*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        version: ["ubuntu:resolute", "ubuntu:noble", "ubuntu:jammy", "ubuntu:focal", "debian:trixie", "debian:bookworm", "debian:bullseye"]
      fail-fast: false

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Compile ${{ matrix.version }} on ${{ matrix.os }}"
        run: |
          ./pullsrc.sh
          docker run --rm -v ${{ github.workspace }}:/work -w /work library/${{ matrix.version }} bash -c "./install_deps.sh && ./compile.sh"

      - name: "Install test with ${{ matrix.version }}"
        run: |
          docker run --rm -v ${{ github.workspace }}:/work -w /work library/${{ matrix.version }} bash -c "apt update && apt install -y --no-install-recommends ./output/*.deb && ssh -V"

      - name: Set artifact name
        id: artifact
        run: echo "name=$(echo ${{ matrix.version }} | sed 's/:/-/g')-${{ matrix.os }}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: ${{ github.workspace }}/output/*.deb

  create_release:
    # if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./output
          merge-multiple: true

      # - name: Get tag message
      #   run: |
      #     echo -e "> Automated release created by GitHub Actions.\n" > ${{ github.workspace }}/RELEASE.md
      #     GITHUB_REF=${{ github.ref }}
      #     TAG_NAME="${GITHUB_REF#refs/tags/}"
      #     git tag -l --format='%(contents)' "${TAG_NAME}" | tee -a ${{ github.workspace }}/RELEASE.md

      # - name: Create Release
      #   id: create_release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "${{ github.workspace }}/output/*.deb"
      #     bodyFile: ${{ github.workspace }}/RELEASE.md
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     allowUpdates: true
      - name: Publish release
        run: |
          set -xe
          sudo apt-get install \
            zip \
            unzip
          source version.env
          sudo timedatectl set-timezone Asia/Shanghai
          export build_timestamp="$(date +'%Y%m%d_%H%M')"
          echo -e "> Automated release OpenSSH_${OPENSSHVER} with OpenSSL_${OPENSSLVER}.\n" > ${{ github.workspace }}/RELEASE.md
          cat <<'EOF' >> ${{ github.workspace }}/RELEASE.md
          # Proxy download:
          ```bash
          curl -#Lo openssh-indiff.zip "https://ghproxy.it/https://github.com/indiff/openssh-deb/releases/download/OpenSSH_shitver_shitstamp/openssh_resolute_26.04_shitstamp.x86_64.zip"
          ```
            
          # Direct download:
          ```bash         
          curl -#Lo openssh-indiff.zip "https://github.com/indiff/openssh-rpms/releases/download/OpenSSH_shitver_shitstamp/openssh_resolute_26.04_shitstamp.x86_64.zip"
          ```

          ```
          ls -l output/*.deb
          sudo apt install -y output/*.deb
          ```
          ```
          cat << 'EOF' > /etc/ssh/sshd_config
          Port 22
          AddressFamily inet
          PubkeyAcceptedAlgorithms +ssh-rsa
          PermitRootLogin yes
          PasswordAuthentication yes
          UseDNS no
          UsePAM yes
          TCPKeepAlive yes
          ClientAliveInterval 60
          ClientAliveCountMax 3
          #Subsystem sftp  internal-sftp
          Subsystem sftp  /usr/libexec/openssh/sftp-server
          KexAlgorithms -diffie-hellman-group1-sha1,diffie-hellman-group1-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group15-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha256,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha512
          shitshit
          ```
          EOF
          sed -i "s/shitver/${OPENSSHVER}/g" RELEASE.md
          sed -i "s/shitstamp/${build_timestamp}/g" RELEASE.md
          sed -i 's/shitshit/EOF/g' RELEASE.md
          mkdir -p ${{ github.workspace }}/zip
          cd ${{ github.workspace }}/output/
          #         version: ["ubuntu:noble", "ubuntu:jammy", "ubuntu:focal", "debian:trixie", "debian:bookworm", "debian:bullseye"]
          # ubuntu:noble	24.04	Noble Numbat	2024年4月	长期支持版（LTS），当前最新
          # ubuntu:jammy	22.04	Jammy Jellyfish	2022年4月	长期支持版（LTS）
          # ubuntu:focal	20.04	Focal Fossa	2020年4月	长期支持版（LTS），将于2025年4月结束标准支持
          # debian:trixie	13	Trixie	预计2025年	当前为 testing 版本
          # debian:bookworm	12	Bookworm	2023年6月	当前稳定版（old stable）
          # debian:bullseye	11	Bullseye	2021年8月	旧稳定版（oldstable）
          # ubuntu:resolute 26.04
          zip -q -9 ${{ github.workspace }}/zip/openssh_resolute_26.04_${build_timestamp}.x86_64.zip ./*resolute*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_noble_24.04_${build_timestamp}.x86_64.zip ./*noble*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_jammy_22.04_${build_timestamp}.x86_64.zip ./*jammy*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_focal_20.04_${build_timestamp}.x86_64.zip ./*focal*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_trixie_13_${build_timestamp}.x86_64.zip ./*trixie*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_bookworm_12_${build_timestamp}.x86_64.zip ./*bookworm*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_bullseye_11_${build_timestamp}.x86_64.zip ./*bullseye*.deb
          GITHUB_REF=${{ github.ref }}
          TAGNAME="OpenSSH_${OPENSSHVER}_${build_timestamp}"
          NAME="${TAGNAME}"
          git tag -l --format='%(contents)' "${TAGNAME}" | tee -a ${{ github.workspace }}/RELEASE.md
          gh release delete --cleanup-tag --yes "$TAGNAME" || true
          # gh release create "$TAGNAME" --target "master" -F ${{ github.workspace }}/RELEASE.md --title "$NAME" ${{ github.workspace }}/zip/*
          gh release create "$TAGNAME" \
              --target "${GITHUB_SHA}" \
              -F "${{ github.workspace }}/RELEASE.md" \
              --title "$NAME" \
              "${{ github.workspace }}/zip/*"
        env:
          GITHUB_TOKEN: ${{ github.token }}
