# This is a basic workflow to help you get started with Actions

name: Create release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags: [ "v*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        version: ["ubuntu:noble", "ubuntu:jammy", "ubuntu:focal", "debian:trixie", "debian:bookworm", "debian:bullseye"]
      fail-fast: false

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Compile ${{ matrix.version }} on ${{ matrix.os }}"
        run: |
          ./pullsrc.sh
          docker run --rm -v ${{ github.workspace }}:/work -w /work library/${{ matrix.version }} bash -c "./install_deps.sh && ./compile.sh"

      - name: "Install test with ${{ matrix.version }}"
        run: |
          docker run --rm -v ${{ github.workspace }}:/work -w /work library/${{ matrix.version }} bash -c "apt update && apt install -y --no-install-recommends ./output/*.deb && ssh -V"

      - name: Set artifact name
        id: artifact
        run: echo "name=$(echo ${{ matrix.version }} | sed 's/:/-/g')-${{ matrix.os }}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: ${{ github.workspace }}/output/*.deb

  create_release:
    # if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./output
          merge-multiple: true

      # - name: Get tag message
      #   run: |
      #     echo -e "> Automated release created by GitHub Actions.\n" > ${{ github.workspace }}/RELEASE.md
      #     GITHUB_REF=${{ github.ref }}
      #     TAG_NAME="${GITHUB_REF#refs/tags/}"
      #     git tag -l --format='%(contents)' "${TAG_NAME}" | tee -a ${{ github.workspace }}/RELEASE.md

      # - name: Create Release
      #   id: create_release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "${{ github.workspace }}/output/*.deb"
      #     bodyFile: ${{ github.workspace }}/RELEASE.md
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     allowUpdates: true
      - name: Publish release
        run: |
          set -xe
          sudo apt-get install \
            zip \
            unzip
          source version.env
          sudo timedatectl set-timezone Asia/Shanghai
          export build_timestamp="$(date +'%Y%m%d_%H%M')"
          echo -e "> Automated release OpenSSH_${OPENSSHVER} with OpenSSL_${OPENSSLVER}.\n" > ${{ github.workspace }}/RELEASE.md
          cat <<'EOF' >> ${{ github.workspace }}/RELEASE.md
          # Proxy download:
          ```bash
          curl -#Lo openssh-indiff.zip "https://ghproxy.cfd/https://github.com/indiff/openssh-rpms/releases/download/OpenSSH_shitver_shitstamp/openssh_el7_shitstamp.x86_64.zip"
          ```
            
          # Direct download:
          ```bash         
          curl -#Lo openssh-indiff.zip "https://github.com/indiff/openssh-rpms/releases/download/OpenSSH_shitver_shitstamp/openssh_el7_shitstamp.x86_64.zip"
          ```

          ```
          unzip openssh-indiff.zip -d openssh
          cd openssh

          # Backup current SSH config
          [[ -f /etc/ssh/sshd_config ]] && mv /etc/ssh/sshd_config /etc/ssh/sshd_config.$(date +%Y%m%d)

          # Install rpm packages. Exclude all debug packages.
          find . ! -name '*debug*' -name '*.rpm' | xargs sudo yum --disablerepo=* localinstall -y --allowerasing

          # fix by packages.
          yum install -y libICE libSM libX11 libXt
          yum update -y
          find . ! -name '*debug*' -name '*.rpm' | xargs sudo yum --disablerepo=* localinstall -y --skip-broken

          # in case host key files got permissions too open.
          chmod -v 600 /etc/ssh/ssh_host_*_key

          # For CentOS7+:
          # in some cases previously installed systemd unit file is left on disk after upgrade.
          # causes systemd mixing unit files and initscripts units provided by this package.
          if [[ -d /run/systemd/system && -f /usr/lib/systemd/system/sshd.service ]]; then
              mv /usr/lib/systemd/system/sshd.service /usr/lib/systemd/system/sshd.service.$(date +%Y%m%d)
              systemctl daemon-reload
          fi

          # Check Installed version:
          ssh -V && /usr/sbin/sshd -V

          # Restart service
          service sshd restart
          ```
          ```
          yum erase openssh-askpass openssh-keycat openssh-cavs openssh-askpass openssh-askpass-gnome openssh-debuginfo
          rpm -ivh --force --nodeps --replacepkgs --replacefiles openssh-*.rpm
          ```
          ```
          cat << 'EOF' > /etc/ssh/sshd_config
          Port 80
          Port 22
          AddressFamily inet
          PubkeyAcceptedAlgorithms +ssh-rsa
          PermitRootLogin yes
          PasswordAuthentication yes
          UseDNS no
          UsePAM yes
          TCPKeepAlive yes
          ClientAliveInterval 60
          ClientAliveCountMax 3
          #Subsystem sftp  internal-sftp
          Subsystem sftp  /usr/libexec/openssh/sftp-server
          KexAlgorithms -diffie-hellman-group1-sha1,diffie-hellman-group1-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group15-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha256,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha512
          shitshit
          ```
          EOF
          sed -i "s/shitver/${OPENSSHVER}/g" RELEASE.md
          sed -i "s/shitstamp/${build_timestamp}/g" RELEASE.md
          sed -i 's/shitshit/EOF/g' RELEASE.md
          mkdir -p ${{ github.workspace }}/zip
          cd ${{ github.workspace }}/output/
          #         version: ["ubuntu:noble", "ubuntu:jammy", "ubuntu:focal", "debian:trixie", "debian:bookworm", "debian:bullseye"]
          zip -q -9 ${{ github.workspace }}/zip/openssh_noble_${build_timestamp}.x86_64.zip ./*noble*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_jammy_${build_timestamp}.x86_64.zip ./*jammy*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_focal_${build_timestamp}.x86_64.zip ./*focal*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_trixie_${build_timestamp}.x86_64.zip ./*trixie*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_bookworm_${build_timestamp}.x86_64.zip ./*bookworm*.deb
          zip -q -9 ${{ github.workspace }}/zip/openssh_bullseye_${build_timestamp}.x86_64.zip ./*bullseye*.deb
          GITHUB_REF=${{ github.ref }}
          TAGNAME="OpenSSH_${OPENSSHVER}_${build_timestamp}"
          NAME="${TAGNAME}"
          git tag -l --format='%(contents)' "${TAGNAME}" | tee -a ${{ github.workspace }}/RELEASE.md
          gh release delete --cleanup-tag --yes "$TAGNAME" || true
          gh release create "$TAGNAME" --target "main" -F ${{ github.workspace }}/RELEASE.md --title "$NAME" ${{ github.workspace }}/zip/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
